import Head from "next/head";
import { useEffect } from "react";

import { Footer, Navbar } from "../components";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Tailwind Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Lexend+Deca:100,200,300,regular,500,600,700,800,900"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div className="container">{children}</div>
      <Footer />
    </div>
  );
};

export default Layout;
