import Head from "next/head";
import { Footer, Navbar } from "../components";

const Layout = ({ children }) => (
  <div>
    <Head>
      <title>Tailwind Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css?family=Lexend+Deca:100,200,300,regular,500,600,700,800,900"
        rel="stylesheet"
      />
    </Head>
    <Navbar />
    <div className="container pt-24 lg:pt-28 min-h-screen">{children}</div>
    <Footer />
  </div>
);

export default Layout;
